//! # cyFile: Tool to handle archive files for Cangyan
//!
//! cyFile is an open-source project spun off from another open-source project
//! called “[Cangyan](https://github.com/Goolnn/cangyan),” written in the Rust
//! programming language. This tool is designed to efficiently handle archive
//! files (with the `.cy` extension) generated by the Cangyan application. Cangyan
//! is a tool developed to simplify the work of translation teams in translation,
//! retouching, and image typesetting tasks. By integrating commonly used features
//! for translation workflows, it improves efficiency and reduces communication
//! costs between different groups within the team.
//!
//! While enhancing the functionality of the project, cyFile also emphasizes
//! user-friendliness, ensuring that users can easily adapt to and incorporate it
//! into their workflows without encountering significant learning curves.

pub mod codec;
pub mod file;
pub mod image;

mod date;
mod note;
mod page;
mod project;

pub use date::Date;
pub use file::ExportArguments;
pub use file::File;
pub use file::Version;
pub use image::Image;
pub use note::Note;
pub use note::Text;
pub use page::Page;
pub use project::Project;

use std::io::Read;

pub fn check<S: Read>(mut stream: S) -> bool {
    let mut header = [0; 15];

    if stream.read_exact(&mut header).is_err() {
        return false;
    };

    header == file::data::HEADER_DATA
}

#[cfg(test)]
mod tests {
    use std::io::Seek;
    use std::io::SeekFrom;
    use std::io::Write;

    #[test]
    fn check() -> anyhow::Result<()> {
        let mut file = tempfile::tempfile()?;

        assert!(!super::check(&file));

        file.write_all("苍眼汉化组".as_bytes())?;
        file.seek(SeekFrom::Start(0))?;

        assert!(super::check(&file));

        Ok(())
    }
}
